trainer: forces

dataset:
  normalize_labels: True
  target_mean: -0.7554450631141663
  target_std: 2.887317180633545
  grad_target_mean: 0.0
  grad_target_std: 2.887317180633545

logger: tensorboard

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True

model:
  name: schnet
  hidden_channels: 1024
  num_filters: 256
  num_interactions: 5
  num_gaussians: 200
  cutoff: 6.0
  use_pbc: True

# *** Important note ***
#   The total number of gpus used for this run was 64.
#   If the global batch size (num_gpus * batch_size) is modified
#   the lr_milestones and warmup_steps need to be adjusted accordingly.

optim:
  batch_size: 20
  eval_batch_size: 20
  eval_every: 10000
  num_workers: 16
  lr_initial: 0.0001
  lr_gamma: 0.1
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 313907
    - 523179
    - 732451
  warmup_steps: 209271
  warmup_factor: 0.2
  max_epochs: 15
  force_coefficient: 30
