trainer: forces

dataset:
  normalize_labels: False

logger: wandb

task:
  dataset: oc22_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  primary_metric: forces_mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True

model:
  name: gemnet_t
  num_spherical: 7
  num_radial: 128
  num_blocks: 3
  emb_size_atom: 512
  emb_size_edge: 512
  emb_size_trip: 64
  emb_size_rbf: 16
  emb_size_cbf: 16
  emb_size_bil_trip: 64
  num_before_skip: 1
  num_after_skip: 2
  num_concat: 1
  num_atom: 3
  cutoff: 6.0
  max_neighbors: 50
  rbf:
    name: gaussian
  envelope:
    name: polynomial
    exponent: 5
  cbf:
    name: spherical_harmonics
  extensive: True
  otf_graph: True
  output_init: HeOrthogonal
  activation: silu
  scale_file: gemnet-dT.json

  regress_forces: True
  direct_forces: True

optim:
  batch_size: 16
  eval_batch_size: 16
  eval_every: 5000
  num_workers: 2
  lr_initial: 5.e-4
  optimizer: AdamW
  optimizer_params: {"amsgrad": True}
  warmup_steps: -1 # don't warm-up the learning rate
  # warmup_factor: 0.2
  lr_gamma: 0.8
  # Following calculation is for an effective batch size of 16 x 16 GPUs = 256
  # and a dataset size of 8225293 (1 epoch = 32130 steps).
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 64000 # ~2 epochs
    - 96000 # ~3 epochs
    - 128000 # ~4 epochs
    - 160000 # ~5 epochs
    - 192000 # ~6 epochs
  max_epochs: 80
  ema_decay: 0.999
  clip_grad_norm: 10
  loss_energy: mae
  loss_force: atomwisel2
  force_coefficient: 1
  energy_coefficient: 1
