trainer: forces

normalizer:
  normalize_labels: True
  target_mean: -0.7554450631141663
  target_std: 2.887317180633545
  grad_target_mean: 0.0
  grad_target_std: 2.887317180633545

logger: tensorboard

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True

model:
  name: cgcnn
  atom_embedding_size: 512
  fc_feat_size: 128
  num_fc_layers: 3
  num_graph_conv_layers: 3
  cutoff: 6.0
  num_gaussians: 100
  use_pbc: True

# *** Important note ***
#   The total number of gpus used for this run was 32.
#   If the global batch size (num_gpus * batch_size) is modified
#   the lr_milestones and warmup_steps need to be adjusted accordingly.

optim:
  batch_size: 24
  eval_batch_size: 24
  num_workers: 16
  lr_initial: 0.0005
  lr_gamma: 0.1
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 523179
    - 871966
    - 1220752
  warmup_steps: 348786
  warmup_factor: 0.2
  max_epochs: 20
  force_coefficient: 10
